insert into ORG_NODE_ANCESTOR (ANCESTOR_ORG_NODE_ID, ORG_NODE_ID, NUMBER_OF_LEVELS, CREATED_BY, CREATED_DATE_TIME, UPDATED_BY, DATA_IMPORT_HISTORY_ID, UPDATED_DATE_TIME)
values (1, 1, 0, 1, to_date('28-10-2014 12:55:07', 'dd-mm-yyyy hh24:mi:ss'), null, null, null);

insert into ORG_NODE_ANCESTOR (ANCESTOR_ORG_NODE_ID, ORG_NODE_ID, NUMBER_OF_LEVELS, CREATED_BY, CREATED_DATE_TIME, UPDATED_BY, DATA_IMPORT_HISTORY_ID, UPDATED_DATE_TIME)
values (1, 2, 1, 1, to_date('28-10-2014 12:55:07', 'dd-mm-yyyy hh24:mi:ss'), null, null, null);

insert into ORG_NODE_ANCESTOR (ANCESTOR_ORG_NODE_ID, ORG_NODE_ID, NUMBER_OF_LEVELS, CREATED_BY, CREATED_DATE_TIME, UPDATED_BY, DATA_IMPORT_HISTORY_ID, UPDATED_DATE_TIME)
values (2, 2, 0, 1, to_date('28-10-2014 12:55:07', 'dd-mm-yyyy hh24:mi:ss'), null, null, null);

